server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэш для статических файлов
    location /public/ {
        expires 30d;
        add_header Cache-Control "public";
    }

    # Service Worker (важно для PWA)
    location = /sw.js {
        add_header Cache-Control "no-cache";
    }
}